#!/usr/bin/env python3
"""Regenerates src/deviceid_data.rs from the APRS device identification database
(https://github.com/aprsorg/aprs-deviceid, CC BY-SA 2.0, maintained by OH7LZB).

Usage: scripts/update-deviceid.py <path to a clone of aprsorg/aprs-deviceid>

Contact addresses are dropped; everything the library uses is kept as it is.
"""
import pathlib, subprocess, sys

import yaml

src = pathlib.Path(sys.argv[1])
db = yaml.safe_load((src / "tocalls.yaml").read_text(encoding="utf-8"))
commit = subprocess.run(["git", "-C", str(src), "log", "-1", "--format=%H %cs"],
                        capture_output=True, text=True, check=True).stdout.strip()


def s(v):
    if v is None:
        return "None"
    return 'Some("' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '")'


def features(e):
    return "&[" + ", ".join('"' + f + '"' for f in e.get("features", [])) + "]"


lines = [
    "// Generated by scripts/update-deviceid.py from aprsorg/aprs-deviceid. Do not edit.",
    "// Source: https://github.com/aprsorg/aprs-deviceid, CC BY-SA 2.0, maintained by OH7LZB.",
    "",
    "use crate::deviceid::{Entry, Legacy, Suffix};",
    "",
    f'pub(crate) const COMMIT: &str = "{commit}";',
    "",
    "pub(crate) static TOCALLS: &[Entry] = &[",
]
for t in db["tocalls"]:
    lines.append(f'    Entry {{ pattern: "{t["tocall"]}", vendor: {s(t.get("vendor"))}, model: {s(t.get("model"))}, class: {s(t.get("class"))}, os: {s(t.get("os"))}, features: {features(t)} }},')
lines += ["];", "", "pub(crate) static MICE: &[Suffix] = &["]
for m in db["mice"]:
    lines.append(f'    Suffix {{ suffix: "{m["suffix"].replace(chr(92), chr(92) * 2).replace(chr(34), chr(92) + chr(34))}", vendor: {s(m.get("vendor"))}, model: {s(m.get("model"))}, class: {s(m.get("class"))}, os: {s(m.get("os"))}, features: {features(m)} }},')
lines += ["];", "", "pub(crate) static MICE_LEGACY: &[Legacy] = &["]
for m in db["micelegacy"]:
    suffix = f'Some("{m["suffix"]}")' if "suffix" in m else "None"
    lines.append(f'    Legacy {{ prefix: "{m["prefix"]}", suffix: {suffix}, vendor: {s(m.get("vendor"))}, model: {s(m.get("model"))}, class: {s(m.get("class"))}, os: {s(m.get("os"))}, features: {features(m)} }},')
lines += ["];", ""]
dest = pathlib.Path(__file__).resolve().parent.parent / "src" / "deviceid_data.rs"
dest.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {dest} ({len(db['tocalls'])} tocalls, {len(db['mice'])} mice, {len(db['micelegacy'])} legacy) from {commit}")
